modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config="mechanical_drive.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Create Mechanical Drive"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="mechanical_drive_logo.png"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="create"
    type="required"
    versionRange="[6.0.10,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ponder"
    type="required"
    versionRange="[1.0.82,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="sable"
    type="required"
    versionRange="[2.0.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="simulated"
    type="required"
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="offroad"
    type="required"
    versionRange="[1.3.0,)"
    ordering="AFTER"
    side="BOTH"
